import React, { useRef } from 'react'
import html2canvas from 'html2canvas'
import jsPDF from 'jspdf'

export default function Report({ report, onBack }){
  const ref = useRef()

  async function downloadPDF(){
    const el = ref.current
    const canvas = await html2canvas(el, { scale: 2 })
    const imgData = canvas.toDataURL('image/png')
    const pdf = new jsPDF('p','mm','a4')
    const imgProps = pdf.getImageProperties(imgData)
    const pdfWidth = 210
    const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width
    pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight)
    pdf.save(`${report.vehicle.model.replace(/\s+/g,'_')}_inspection.pdf`)
  }

  function printReport(){
    window.print()
  }

  return (
    <div>
      <div className="mb-4 flex items-center justify-between no-print">
        <div>
          <h2 className="text-xl font-semibold">Inspection Report</h2>
          <div className="text-sm text-slate-500">{report.vehicle.model} — {report.vehicle.reg}</div>
        </div>
        <div className="flex gap-2">
          <button onClick={onBack} className="rounded-full border border-slate-200 px-4 py-2 text-sm text-slate-700">Back</button>
          <button onClick={printReport} className="rounded-full bg-slate-100 px-4 py-2 text-sm text-slate-700">Print Report</button>
          <button onClick={downloadPDF} className="rounded-full bg-slate-900 px-4 py-2 text-sm text-white">Download PDF</button>
        </div>
      </div>

      <div ref={ref} className="print-page rounded-2xl border border-white/70 bg-white/80 p-6 shadow-sm backdrop-blur">
        <div className="mb-4 flex justify-between">
          <div>
            <div className="text-sm text-slate-600">Inspection Date</div>
            <div className="font-medium">{new Date(report.date).toLocaleString()}</div>
          </div>
          <div>
            <div className="text-sm text-slate-600">Recommended Action</div>
            <div className="font-medium">{report.recommendedAction}</div>
          </div>
        </div>

        <section className="mb-4">
          <h3 className="text-sm text-slate-600">Vehicle</h3>
          <div className="font-medium text-lg">{report.vehicle.model} — {report.vehicle.reg}</div>
        </section>

        <section className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-4">
          <div>
            <div className="text-sm text-slate-600">Mileage</div>
            <div className="font-medium">{report.mileage}</div>
          </div>
          <div>
            <div className="text-sm text-slate-600">Fuel Level</div>
            <div className="font-medium">{report.fuel}%</div>
          </div>
          <div>
            <div className="text-sm text-slate-600">Operator Notes</div>
            <div className="font-medium">{report.notes || '—'}</div>
          </div>
        </section>

        <section className="mb-4">
          <h3 className="text-sm text-slate-600 mb-2">Damage Findings</h3>
          {report.findings && report.findings.length>0 ? (
            <ul className="space-y-2">
              {report.findings.map((f,i)=> (
                <li key={i} className="p-3 border rounded">
                  <div className="font-medium">{f.title}</div>
                  <div className="text-xs text-slate-500">Confidence: {(f.confidence*100).toFixed(0)}% — Severity: {f.severity}</div>
                </li>
              ))}
            </ul>
          ) : (
            <div className="text-sm text-slate-500">No issues detected.</div>
          )}
        </section>

        <section>
          <h3 className="text-sm text-slate-600 mb-2">Photos</h3>
          <div className="grid grid-cols-2 gap-3 md:grid-cols-3">
            {(report.images || []).map((im, i) => (
              <img key={i} src={im.url} alt={`photo-${i}`} className="h-32 w-full rounded-xl object-cover" />
            ))}
          </div>
        </section>

        <footer className="mt-6 text-xs text-slate-500">Generated by FleetInspect AI — Prototype</footer>
      </div>
    </div>
  )
}
